FROM openjdk:17 as build
COPY . /workspace
WORKDIR /workspace
RUN ./mvnw package -DskipTests

FROM azul/zulu-openjdk-alpine:17
COPY --from=build /workspace/target/*.jar /app/app-runner.jar
WORKDIR /app
EXPOSE 8080
ENTRYPOINT [ "java","-jar" ]
CMD ["app-runner.jar"]